version: '3.9'
services:
  redis:
    image: redis:7.0.9-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  cache-api:
    build: .
    ports:
      - "80:80"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - VIDEOS_URL=http://video_reader:5000/videos
      - VIDEO_URL=http://video_reader:5000/videos/{id}
    depends_on:
      - redis
      - video_reader
  video_reader:
    image: video-reader
    ports:
      - "5000:5000"

volumes:
  redis_data:
