version: '3.9'
services:
  redis:
    image: redis:7.0.9-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass redis
volumes:
  redis_data:
