name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ba-video-cacher .

    - name: Run tests
      run: docker run -e CI=true ${{ secrets.DOCKERHUB_USERNAME }}/ba-video-cacher pytest 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to registry
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ba-video-cacher
